# Generated by Django 4.1.7 on 2023-07-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enroll_id", models.CharField(max_length=20)),
                ("class_id", models.CharField(max_length=20)),
                ("section_id", models.CharField(max_length=20)),
                ("doj", models.DateField()),
                ("session", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Csv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.FileField(upload_to="csvs")),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("activated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("gender", models.CharField(max_length=20)),
                ("aadhar", models.CharField(max_length=20)),
                ("dob", models.DateField()),
                ("id_mark", models.CharField(max_length=250)),
                ("addmission_cat", models.CharField(max_length=50)),
                ("height", models.CharField(max_length=30)),
                ("weight", models.CharField(max_length=30)),
                ("mail", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=13)),
                ("address", models.CharField(max_length=100)),
                (
                    "enroll_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habrieapp.academicdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("father_name", models.CharField(max_length=30)),
                ("father_qualification", models.CharField(max_length=30)),
                ("father_profession", models.CharField(max_length=30)),
                ("father_designation", models.CharField(max_length=250)),
                ("father_aadhar", models.CharField(max_length=20)),
                ("father_number", models.CharField(max_length=13)),
                ("father_mail", models.EmailField(max_length=254)),
                ("mother_name", models.CharField(max_length=30)),
                ("mother_qualification", models.CharField(max_length=13)),
                ("mother_profession", models.CharField(max_length=100)),
                ("mother_designation", models.CharField(max_length=100)),
                ("mother_aadhar", models.CharField(max_length=30)),
                ("mother_number", models.CharField(max_length=13)),
                ("mother_mail", models.EmailField(max_length=254)),
                (
                    "student_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habrieapp.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_name", models.FileField(null=True, upload_to="document")),
                (
                    "student_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habrieapp.student",
                    ),
                ),
            ],
        ),
    ]
